FROM mcr.microsoft.com/dotnet/aspnet:9.0  AS base
COPY bin/Release/net9.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p e7048812-4948-4acd-91ba-4a61dc1b2a2f

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "AbpTodoApp.HttpApi.Host.dll"]